### ISSUE TITLE
TODO: rating

### ISSUE THREAD

**Issue by 2455DD** [2455DD/akari#3]
query and save rating of a picture and
- [x] query the rating
- [x] save the rating in the db
- [ ] move the pictures with the certain rating to given folder

**Comment by 2455DD** [comment]
it seems that the gui crashes during migrating database from json to sqlite
- [ ] fix gui
